# Site
repository: amirali-esmaili83.github.io

# Content configuration version
version: 2

# Personal info
name: AmirAli Esmaili
title: Backend Developer
email: amiraliesmaeli741@gmail.com
website: https://amirali-esmaili83.github.io/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username: amirali-esmaili83
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: https://www.linkedin.com/in/amirali-esmaili-6851512b9/
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
# additional_links:
# - title: Link name
  # icon: Font Awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
  # url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.jpg

about_content: | 
  Computer Engineering student at the University of Science and Culture with a focus on backend development using Python and Django.

  Experienced in building web applications and REST APIs, with a strong interest in software engineering and backend systems.

  Currently expanding my knowledge in Artificial Intelligence and Data Science alongside backend development.
content:
  - title: Education
    layout: list
    content:
      - layout: top-middle
        title: University of Science and Culture
        sub_title: B.Sc in Computer Engineering
        caption: 2023 - Present
        # description: |  this will include new lines to allow paragraphs
  # - title: Experience
    # layout: list
    # content:
    #   - layout: right
    #     title: Company name
    #     sub_title: Job title
    #     caption: Date Range (eg. November 2016 - present)
    #     link: Link to company (optional)
    #     quote: >
    #       Short description of the company (optional)
        # description: |  this will include new lines to allow paragraphs
          # Description of role
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        border: weak  
        title: ToDo App (Django REST)
        link: https://github.com/Amirali-Esmaeli/ToDo-App
        link_text: Project Repository
        description: | # this will include new lines to allow paragraphs
           Developed a Django-based task management system with separate applications for user authentication and task handling.

           Implemented a custom user model with email-based authentication and secure JWT/Token-based authentication system for login, registration, password management, and account verification.

           Designed a multi-user task management system with full CRUD functionality and strict data isolation using Django REST Framework.

           Integrated Celery for scheduled background task execution, Redis for caching and message brokering, and Docker for containerized deployment with PostgreSQL and Nginx.
  - title: Technologies
    layout: list
    content:
      - layout: left
        border: weak
        title: Languages
        description: |
            Python, Javascript, SQL

      - layout: left
        title: Frameworks & Tools
        description: |
              Django, Django REST Framework, Docker, Git, Linux

  - title: Certificates & Education
    layout: list
    content:
      - layout: left
        border: weak
        title: Advanced Django Course
        sub_title: Maktabkhooneh
        link: https://maktabkhooneh.org/certificates/mk-s1wt9n/

      - layout: left
        title: Front-End
        sub_title: Quera
        link: https://quera.org/certificate/3xyYyRvT
  
  - title: Language Skills
    layout: list
    content:
          - layout: left
            border: weak
            title: English
            description: A2 (basic reading of technical documentation)

          - layout: left
            title: Persian
            description: Native
  
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
